### PR TITLE
Use ./configure to detect arc4random and use it if present

### PR DESCRIPTION
**Pull request by renaudallard**
I am not sure you will like this one as it involves using a configure script, but it makes it possible to detect arc4random on systems where it is installed to broaden the list of OSes with more secure functions.
Note that the configure is quite fast.

### CODE REVIEW

**Comment by solusipse** [comment]
I'd like to merge this one into second branch, together with #16. Are you ok with that?

**Comment by renaudallard** [comment]
It's fine for me, it will give some more time to test that way.

**Comment by solusipse** [comment]
I merged this manually into branch [secure](/solusipse/fiche/tree/secure). Thank you!

**Comment by jeaye** [comment]
@solusipse What's the long-term plan for the secure branch? Can we get it into master? If not, can we keep it up to date with master (it's 8 commits behind)?

**Comment by jeaye** [comment]
@solusipse Also, along with this change should come an addition to the REAMDE which mentions the required `./configure` before `make`.

**Pull request closed without merging**
