### PR TITLE
Correct a typo: lenght -> length

### PR DESCRIPTION
**Pull request by renaudallard**
Just a small typo correction because I saw it :D
Second patch solves the issue #14, and seems to work OK on linux too

### CODE REVIEW

**Comment by solusipse** [comment]
Thank you very much for this! I love everything but there's one thing I'd like to change before I'll merge: https://github.com/renaudallard/fiche/commit/d771d7bdfd3953a18e40734cd83a207b133a18c5. Statistically, collision likeliness may seem to be pretty big, but I got some empirical data that shows that with current service usage it barely never happens. For last month, users pasted 1806 pieces of text and there's only one paste that has 5 characters name (and since it actually contains nothing but noise, I can point it here, if you're curious: http://termbin.com/jupu6 :) ). I'd like also to keep old set of characters, at least in the main branch ("abcdefghijklmnopqrstuvwxyz0123456789"), it's just easier to remember or retype url on second terminal. I think that maybe the best option would be to leave that choice to end user and add appropriate options to `getopt`: https://github.com/solusipse/fiche/blob/master/fiche.c#L367. What do you think about this? Would you like me to merge it now and add this functionality, or would you like to write this one also? :)

**Comment by renaudallard** [comment]
Yes, it might be a good idea to add the extended charset to either makefile or getopt. Maybe merge everything except d771d7b. I will have a look at providing an option for it.

**Comment by renaudallard** [comment]
I have added the -e option for using the extended charset

**Comment by solusipse** [comment]
Thank you!

**Pull request merged**
