### PR TITLE
Add basic Dockerfile for multistage build

### PR DESCRIPTION
**Pull request by dschaper**
Multstage build of rewrite code. Docker-compose file is in-work for submission.

### CODE REVIEW

**Comment by solusipse** [comment]
Thank you! Sorry for the delay. I've noticed that meanwhile there was another contribution adding support for Docker: https://github.com/solusipse/fiche/pull/75. Could you please take a look at it and let me know which one, in your opinion, should I merge in?

**Comment by dschaper** [comment]
No problem, the changes could be merged in to #75. My changes are mostly to using the Docker build stage pattern and that can be added to any options. If @M0nsieurChat is open to it, I can merge my changes in to his PR. He's got the documentation done and the added docker-compose file with `nginx` support so that feels like a better fit.

**Comment by dschaper** [comment]
Looking over #75, it would fit right in, my multistage build would handle building the binary in a cleanroom environment, and then copy over the binary to the final stage. This leads to a lighter image and the final image doesn't have the added collateral that the build stage imports.

**Comment by M0nsieurChat** [comment]
Hello, 
No problem for me as well ! 

Regards,

**Comment by dschaper** [comment]
Great! I know staged builds requires a more recent Docker version, but I'm pretty confident that it's mainstream now, even Travis has the required version in their build structure. I'm more of a CircleCI and Drone user, they are covered as well.

**Comment by dschaper** [comment]
Closing for a new PR with updated changes on a new PR.

**Comment by dschaper** [comment]
I was going to just add my changes to the existing PR, but looking that over, I think it may be over complicated for a docker container. It's set up for docker-compose and orchestration and while that is nice, just a simple docker image with the existing default port 9999 exposed and the default `./code` directory is fine. The users can map their desired ports to 9999 and volume mount via their preferred methods to `./code` for the storage directory. No need for an additional `nginx` configuration for just a base image, that can be added but a vast majority of users aren't going to need a load balancer or orchestration manager for just use of Fiche.

**Comment by M0nsieurChat** [comment]
The aim was to provide a quick mean of testing / deploying fiche with all the dependencies (webserver included) as this is what docker does best.

I think both of our visions can be provided in a future PR with : 
  - a Dockerfile + README explaining how to run just fiche by itself with or without host mounts (as you suggested)
  - a docker-compose + README explaining how to run a ready-to-use fiche+nginx on your local machine or remote server

The fiche docker image being used by the docker-compose needs to be the same as the one generated by the Dockerfile.

**Comment by dschaper** [comment]
Thanks for the comments, I agree with everything you said. For now, I'm running the following Dockerfile

```FROM alpine:3.7 as build

RUN apk update && apk add \
    curl \
    gcc \
    make \
    musl-dev

WORKDIR /usr/src/fiche

COPY * ./

RUN make -f Makefile clean \
    && make -f Makefile \
    && make -f Makefile install

FROM alpine:3.7

COPY --from=build /usr/local/bin/fiche /usr/local/bin

RUN apk add --no-cache tini

RUN addgroup -g 901 fiche \
    && adduser -G fiche -D -u 901 fiche \
    && mkdir /code \
    && chown fiche:fiche /code

USER fiche

EXPOSE 9999

VOLUME ["/data"]

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/fiche", "-l", "/dev/stdout"]
```

Invocation is:
`docker run -d --rm -p 9999:9999 -v fiche:/data --name fiche <image> -S -s 8 -d example.com`

That runs the fiche server as a daemon, maps the external port of your choice to `9999` internally and then your choice of mounts, in this case a named volume, to `/data` as exported. If you chose to bind mount, there is the caveat of requiring the mount point to be owned by `UID 901`, as the original version just used the `fiche` user, and that could end up being undetermined at container runtime. 

I've chosen to use `tini` as the init system so it reaps the process, I was finding that when running as daemon the fiche process was not hearing the HUP and not terminating nicely. I also appended the flag to redirect logfiles to /dev/stdout so that you can run `docker logs -f fiche` and see the logs. Makes it easy to manage the logfiles with your choice of orchestration management. 

Any other flags can be passed on the command line and they are honoured. I didn't think it would require an entrypoint script, everything is nicely handled.

**Comment by solusipse** [comment]
@dschaper @M0nsieurChat many thanks for your work guys! Should we merge in https://github.com/solusipse/fiche/pull/75 or are you planning to open a new pull request? This time I'll be more responsive, I promise. And sorry for the delay, again!

**Pull request closed without merging**
