### PR TITLE
added IPv6 support #2

### PR DESCRIPTION
**Pull request by nnnn20430**
this is second attempt to submit pull request to add ipv6 support, last one i noticed something was broken and quickly aborted.

this time it's not middle of night and my eyes are actually open, works properly on my core 2 due "server" (headless laptop) now too, for some reason having some vars declared in if statement didn't work on it worked when i tested on my main pc.... anyway all works now.

### CODE REVIEW

**Comment by solusipse** [comment]
Sorry for the delay. That's cool, I'll review this before weekend. Thanks!

**Comment by nnnn20430** [comment]
You can just tell me if it's terrible.

**Comment by solusipse** [comment]
I'm very sorry for making you wait. To be honest, I'm planning to rewrite whole program, I thought I'll be able to do that earlier. I'm merging this one, thank you very much for your contribution!

**Comment by sbrl** [comment]
Does this PR mean that if I provide `-6`, fiche will listen on both IPv4 _and_ IPv6?

**Comment by nnnn20430** [comment]
yes ipv6 can accept ipv4 connections

**Comment by sbrl** [comment]
@nnnn20430 Cool thanks! :smile:

**Pull request merged**
